import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <header className="flex justify-around bg-[#1f2937] py-4">
                    <Link href="/" className="text-white font-bold">
                        HOME
                    </Link>
                    <Link href="/champions" className="text-white font-bold">
                        CHAMPIONS
                    </Link>
                    <Link href="/items" className="text-white font-bold">
                        ITEMS
                    </Link>
                    <Link href="/rotation" className="text-white font-bold">
                        ROTATION
                    </Link>
                </header>
                {children}
            </body>
        </html>
    );
}
