import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';
import Providers from '@/providers/TanstackProvider';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <header className="sticky top-0 bg-gray-800">
                    <div className="max-w-[1200px] flex justify-around py-4 mx-auto">
                        <Link href="/" className="text-white font-bold">
                            HOME
                        </Link>
                        <Link href="/champions" className="text-white font-bold">
                            CHAMPIONS
                        </Link>
                        <Link href="/items" className="text-white font-bold">
                            ITEMS
                        </Link>
                        <Link href="/rotation" className="text-white font-bold">
                            ROTATION
                        </Link>
                    </div>
                </header>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
